// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/guckppap/gukppap-backend/internal/adpater/repository/mysql/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/guckppap/gukppap-backend/internal/adpater/repository/mysql/ent/shortcut"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Shortcut is the client for interacting with the Shortcut builders.
	Shortcut *ShortcutClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Shortcut = NewShortcutClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Shortcut: NewShortcutClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Shortcut: NewShortcutClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Shortcut.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Shortcut.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Shortcut.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ShortcutMutation:
		return c.Shortcut.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ShortcutClient is a client for the Shortcut schema.
type ShortcutClient struct {
	config
}

// NewShortcutClient returns a client for the Shortcut from the given config.
func NewShortcutClient(c config) *ShortcutClient {
	return &ShortcutClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `shortcut.Hooks(f(g(h())))`.
func (c *ShortcutClient) Use(hooks ...Hook) {
	c.hooks.Shortcut = append(c.hooks.Shortcut, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `shortcut.Intercept(f(g(h())))`.
func (c *ShortcutClient) Intercept(interceptors ...Interceptor) {
	c.inters.Shortcut = append(c.inters.Shortcut, interceptors...)
}

// Create returns a builder for creating a Shortcut entity.
func (c *ShortcutClient) Create() *ShortcutCreate {
	mutation := newShortcutMutation(c.config, OpCreate)
	return &ShortcutCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Shortcut entities.
func (c *ShortcutClient) CreateBulk(builders ...*ShortcutCreate) *ShortcutCreateBulk {
	return &ShortcutCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ShortcutClient) MapCreateBulk(slice any, setFunc func(*ShortcutCreate, int)) *ShortcutCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ShortcutCreateBulk{err: fmt.Errorf("calling to ShortcutClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ShortcutCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ShortcutCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Shortcut.
func (c *ShortcutClient) Update() *ShortcutUpdate {
	mutation := newShortcutMutation(c.config, OpUpdate)
	return &ShortcutUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShortcutClient) UpdateOne(s *Shortcut) *ShortcutUpdateOne {
	mutation := newShortcutMutation(c.config, OpUpdateOne, withShortcut(s))
	return &ShortcutUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShortcutClient) UpdateOneID(id int) *ShortcutUpdateOne {
	mutation := newShortcutMutation(c.config, OpUpdateOne, withShortcutID(id))
	return &ShortcutUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Shortcut.
func (c *ShortcutClient) Delete() *ShortcutDelete {
	mutation := newShortcutMutation(c.config, OpDelete)
	return &ShortcutDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ShortcutClient) DeleteOne(s *Shortcut) *ShortcutDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ShortcutClient) DeleteOneID(id int) *ShortcutDeleteOne {
	builder := c.Delete().Where(shortcut.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShortcutDeleteOne{builder}
}

// Query returns a query builder for Shortcut.
func (c *ShortcutClient) Query() *ShortcutQuery {
	return &ShortcutQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeShortcut},
		inters: c.Interceptors(),
	}
}

// Get returns a Shortcut entity by its id.
func (c *ShortcutClient) Get(ctx context.Context, id int) (*Shortcut, error) {
	return c.Query().Where(shortcut.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShortcutClient) GetX(ctx context.Context, id int) *Shortcut {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ShortcutClient) Hooks() []Hook {
	return c.hooks.Shortcut
}

// Interceptors returns the client interceptors.
func (c *ShortcutClient) Interceptors() []Interceptor {
	return c.inters.Shortcut
}

func (c *ShortcutClient) mutate(ctx context.Context, m *ShortcutMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ShortcutCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ShortcutUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ShortcutUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ShortcutDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Shortcut mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Shortcut []ent.Hook
	}
	inters struct {
		Shortcut []ent.Interceptor
	}
)
