// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/guckppap/gukppap-backend/internal/adpater/repository/mysql/ent/predicate"
	"github.com/guckppap/gukppap-backend/internal/adpater/repository/mysql/ent/shortcut"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeShortcut = "Shortcut"
)

// ShortcutMutation represents an operation that mutates the Shortcut nodes in the graph.
type ShortcutMutation struct {
	config
	op            Op
	typ           string
	id            *int
	url           *string
	shortcut      *string
	exp           *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Shortcut, error)
	predicates    []predicate.Shortcut
}

var _ ent.Mutation = (*ShortcutMutation)(nil)

// shortcutOption allows management of the mutation configuration using functional options.
type shortcutOption func(*ShortcutMutation)

// newShortcutMutation creates new mutation for the Shortcut entity.
func newShortcutMutation(c config, op Op, opts ...shortcutOption) *ShortcutMutation {
	m := &ShortcutMutation{
		config:        c,
		op:            op,
		typ:           TypeShortcut,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withShortcutID sets the ID field of the mutation.
func withShortcutID(id int) shortcutOption {
	return func(m *ShortcutMutation) {
		var (
			err   error
			once  sync.Once
			value *Shortcut
		)
		m.oldValue = func(ctx context.Context) (*Shortcut, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Shortcut.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withShortcut sets the old Shortcut of the mutation.
func withShortcut(node *Shortcut) shortcutOption {
	return func(m *ShortcutMutation) {
		m.oldValue = func(context.Context) (*Shortcut, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ShortcutMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ShortcutMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ShortcutMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ShortcutMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Shortcut.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetURL sets the "url" field.
func (m *ShortcutMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *ShortcutMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the Shortcut entity.
// If the Shortcut object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShortcutMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *ShortcutMutation) ResetURL() {
	m.url = nil
}

// SetShortcut sets the "shortcut" field.
func (m *ShortcutMutation) SetShortcut(s string) {
	m.shortcut = &s
}

// Shortcut returns the value of the "shortcut" field in the mutation.
func (m *ShortcutMutation) Shortcut() (r string, exists bool) {
	v := m.shortcut
	if v == nil {
		return
	}
	return *v, true
}

// OldShortcut returns the old "shortcut" field's value of the Shortcut entity.
// If the Shortcut object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShortcutMutation) OldShortcut(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldShortcut is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldShortcut requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldShortcut: %w", err)
	}
	return oldValue.Shortcut, nil
}

// ResetShortcut resets all changes to the "shortcut" field.
func (m *ShortcutMutation) ResetShortcut() {
	m.shortcut = nil
}

// SetExp sets the "exp" field.
func (m *ShortcutMutation) SetExp(t time.Time) {
	m.exp = &t
}

// Exp returns the value of the "exp" field in the mutation.
func (m *ShortcutMutation) Exp() (r time.Time, exists bool) {
	v := m.exp
	if v == nil {
		return
	}
	return *v, true
}

// OldExp returns the old "exp" field's value of the Shortcut entity.
// If the Shortcut object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShortcutMutation) OldExp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExp: %w", err)
	}
	return oldValue.Exp, nil
}

// ResetExp resets all changes to the "exp" field.
func (m *ShortcutMutation) ResetExp() {
	m.exp = nil
}

// Where appends a list predicates to the ShortcutMutation builder.
func (m *ShortcutMutation) Where(ps ...predicate.Shortcut) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ShortcutMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ShortcutMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Shortcut, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ShortcutMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ShortcutMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Shortcut).
func (m *ShortcutMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ShortcutMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.url != nil {
		fields = append(fields, shortcut.FieldURL)
	}
	if m.shortcut != nil {
		fields = append(fields, shortcut.FieldShortcut)
	}
	if m.exp != nil {
		fields = append(fields, shortcut.FieldExp)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ShortcutMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case shortcut.FieldURL:
		return m.URL()
	case shortcut.FieldShortcut:
		return m.Shortcut()
	case shortcut.FieldExp:
		return m.Exp()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ShortcutMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case shortcut.FieldURL:
		return m.OldURL(ctx)
	case shortcut.FieldShortcut:
		return m.OldShortcut(ctx)
	case shortcut.FieldExp:
		return m.OldExp(ctx)
	}
	return nil, fmt.Errorf("unknown Shortcut field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ShortcutMutation) SetField(name string, value ent.Value) error {
	switch name {
	case shortcut.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case shortcut.FieldShortcut:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetShortcut(v)
		return nil
	case shortcut.FieldExp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExp(v)
		return nil
	}
	return fmt.Errorf("unknown Shortcut field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ShortcutMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ShortcutMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ShortcutMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Shortcut numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ShortcutMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ShortcutMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ShortcutMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Shortcut nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ShortcutMutation) ResetField(name string) error {
	switch name {
	case shortcut.FieldURL:
		m.ResetURL()
		return nil
	case shortcut.FieldShortcut:
		m.ResetShortcut()
		return nil
	case shortcut.FieldExp:
		m.ResetExp()
		return nil
	}
	return fmt.Errorf("unknown Shortcut field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ShortcutMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ShortcutMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ShortcutMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ShortcutMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ShortcutMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ShortcutMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ShortcutMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Shortcut unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ShortcutMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Shortcut edge %s", name)
}
