// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/guckppap/gukppap-backend/internal/adpater/repository/mysql/ent/schema"
	"github.com/guckppap/gukppap-backend/internal/adpater/repository/mysql/ent/shortcut"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	shortcutFields := schema.Shortcut{}.Fields()
	_ = shortcutFields
	// shortcutDescURL is the schema descriptor for url field.
	shortcutDescURL := shortcutFields[0].Descriptor()
	// shortcut.URLValidator is a validator for the "url" field. It is called by the builders before save.
	shortcut.URLValidator = shortcutDescURL.Validators[0].(func(string) error)
	// shortcutDescShortcut is the schema descriptor for shortcut field.
	shortcutDescShortcut := shortcutFields[1].Descriptor()
	// shortcut.ShortcutValidator is a validator for the "shortcut" field. It is called by the builders before save.
	shortcut.ShortcutValidator = shortcutDescShortcut.Validators[0].(func(string) error)
}
