// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guckppap/gukppap-backend/internal/adpater/repository/mysql/ent/shortcut"
)

// ShortcutCreate is the builder for creating a Shortcut entity.
type ShortcutCreate struct {
	config
	mutation *ShortcutMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (sc *ShortcutCreate) SetURL(s string) *ShortcutCreate {
	sc.mutation.SetURL(s)
	return sc
}

// SetShortcut sets the "shortcut" field.
func (sc *ShortcutCreate) SetShortcut(s string) *ShortcutCreate {
	sc.mutation.SetShortcut(s)
	return sc
}

// SetExp sets the "exp" field.
func (sc *ShortcutCreate) SetExp(t time.Time) *ShortcutCreate {
	sc.mutation.SetExp(t)
	return sc
}

// Mutation returns the ShortcutMutation object of the builder.
func (sc *ShortcutCreate) Mutation() *ShortcutMutation {
	return sc.mutation
}

// Save creates the Shortcut in the database.
func (sc *ShortcutCreate) Save(ctx context.Context) (*Shortcut, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ShortcutCreate) SaveX(ctx context.Context) *Shortcut {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *ShortcutCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *ShortcutCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *ShortcutCreate) check() error {
	if _, ok := sc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Shortcut.url"`)}
	}
	if v, ok := sc.mutation.URL(); ok {
		if err := shortcut.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Shortcut.url": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Shortcut(); !ok {
		return &ValidationError{Name: "shortcut", err: errors.New(`ent: missing required field "Shortcut.shortcut"`)}
	}
	if v, ok := sc.mutation.Shortcut(); ok {
		if err := shortcut.ShortcutValidator(v); err != nil {
			return &ValidationError{Name: "shortcut", err: fmt.Errorf(`ent: validator failed for field "Shortcut.shortcut": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Exp(); !ok {
		return &ValidationError{Name: "exp", err: errors.New(`ent: missing required field "Shortcut.exp"`)}
	}
	return nil
}

func (sc *ShortcutCreate) sqlSave(ctx context.Context) (*Shortcut, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *ShortcutCreate) createSpec() (*Shortcut, *sqlgraph.CreateSpec) {
	var (
		_node = &Shortcut{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(shortcut.Table, sqlgraph.NewFieldSpec(shortcut.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.URL(); ok {
		_spec.SetField(shortcut.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := sc.mutation.Shortcut(); ok {
		_spec.SetField(shortcut.FieldShortcut, field.TypeString, value)
		_node.Shortcut = value
	}
	if value, ok := sc.mutation.Exp(); ok {
		_spec.SetField(shortcut.FieldExp, field.TypeTime, value)
		_node.Exp = value
	}
	return _node, _spec
}

// ShortcutCreateBulk is the builder for creating many Shortcut entities in bulk.
type ShortcutCreateBulk struct {
	config
	err      error
	builders []*ShortcutCreate
}

// Save creates the Shortcut entities in the database.
func (scb *ShortcutCreateBulk) Save(ctx context.Context) ([]*Shortcut, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Shortcut, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShortcutMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *ShortcutCreateBulk) SaveX(ctx context.Context) []*Shortcut {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *ShortcutCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *ShortcutCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
