// Code generated by ent, DO NOT EDIT.

package url

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the url type in the database.
	Label = "url"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOriginURL holds the string denoting the origin_url field in the database.
	FieldOriginURL = "origin_url"
	// FieldShortcutURL holds the string denoting the shortcut_url field in the database.
	FieldShortcutURL = "shortcut_url"
	// Table holds the table name of the url in the database.
	Table = "urls"
)

// Columns holds all SQL columns for url fields.
var Columns = []string{
	FieldID,
	FieldOriginURL,
	FieldShortcutURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OriginURLValidator is a validator for the "origin_url" field. It is called by the builders before save.
	OriginURLValidator func(string) error
	// ShortcutURLValidator is a validator for the "shortcut_url" field. It is called by the builders before save.
	ShortcutURLValidator func(string) error
)

// OrderOption defines the ordering options for the Url queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOriginURL orders the results by the origin_url field.
func ByOriginURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginURL, opts...).ToFunc()
}

// ByShortcutURL orders the results by the shortcut_url field.
func ByShortcutURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShortcutURL, opts...).ToFunc()
}
