// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gukppap-backend/internal/adapter/repository/mysql/ent/schema"
	"gukppap-backend/internal/adapter/repository/mysql/ent/url"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	urlFields := schema.Url{}.Fields()
	_ = urlFields
	// urlDescOriginURL is the schema descriptor for origin_url field.
	urlDescOriginURL := urlFields[0].Descriptor()
	// url.OriginURLValidator is a validator for the "origin_url" field. It is called by the builders before save.
	url.OriginURLValidator = urlDescOriginURL.Validators[0].(func(string) error)
	// urlDescShortcutURL is the schema descriptor for shortcut_url field.
	urlDescShortcutURL := urlFields[1].Descriptor()
	// url.ShortcutURLValidator is a validator for the "shortcut_url" field. It is called by the builders before save.
	url.ShortcutURLValidator = urlDescShortcutURL.Validators[0].(func(string) error)
}
